import "../styles/profile_details_forms.css"

export { default as about } from "./AboutYou"
export { default as address } from "./Address"
export { default as language } from "./Language"
export { default as birthday } from "./Birthday"
export { default as lifeEvents } from "./LifeEvents"
export { default as pronunciation } from "./NamePronunciation"
export { default as otherNames } from "./OtherNames"
export { default as city } from "./City"
export { default as phone } from "./PhoneNumber"
export { default as college } from "./College"
export { default as politics } from "./PoliticalViews"
export { default as currentCity } from "./CurrentCity"
export { default as relationship } from "./Relationship"
export { default as family } from "./FamilyMembers"
export { default as religion } from "./ReligiousViews"
export { default as quotes } from "./FavoriteQuotes"
export { default as sexuality } from "./SexualPreference"
export { default as gender } from "./Gender"
export { default as social } from "./SocialLink"
export { default as highSchool } from "./HighSchool"
export { default as website } from "./Website"
export { default as hometown } from "./Hometown"
export { default as workplace } from "./Workplace"